### ISSUE TITLE
Add radio buttons

### ISSUE THREAD

**Issue by mgrazebrook** [lordmauve/python-now#1]
exec = html.INPUT(type='radio', name='mode', value='exec', checked="checked")
eval = html.INPUT(type='radio', name='mode', value='eval')
single = html.INPUT(type='radio', name='mode', value='single')
document <= exec  + html.LABEL('Script')
document <= single + html.LABEL('Expression')

**Comment by lordmauve** [comment]
This is no longer valid; the mode is being supplied from the Markdown
